# https://taskfile.dev
version: '3'

env:
  KO_DOCKER_REPO: registry.yoshino-s.xyz/yoshino-s/image-downloader

tasks:
  tools:
    cmds:
      - echo "Installing tools..."
      - go install github.com/sudorandom/protoc-gen-connect-openapi@latest
      - go install github.com/bufbuild/buf/cmd/buf@latest
      - go install github.com/goreleaser/goreleaser@latest
      - go install github.com/google/ko@latest
  proto:
    cmds:
      - buf generate proto
  build:
    cmds:
      - goreleaser build --snapshot --clean --single-target --skip before